export const queryKeys = {
  workOrders: ['work-orders'] as const,
  workOrder: (id: string) => ['work-orders', id] as const,
  board: (closedDays: number) => ['work-orders', 'board', closedDays] as const,
  statusHistory: (id: string) => ['work-orders', id, 'history'] as const,
  workflowStatuses: ['work-order-statuses'] as const,
  workOrdersFiltered: (filter: { customerId?: string; vehicleId?: string }) => ['work-orders', 'filtered', filter] as const,
  customers: ['customers'] as const,
  customer: (id: string) => ['customers', id] as const,
  customerSearch: (params: object) => ['customers', 'search', params] as const,
  vehicles: ['vehicles'] as const,
  services: ['services'] as const,
  service: (id: string) => ['services', id] as const,
  serviceSearch: (params: object) => ['services', 'search', params] as const,
  servicePrices: (id: string) => ['services', id, 'prices'] as const,
  priceSuggestion: (serviceId: string, vehicleId: string) => ['services', serviceId, 'suggestion', vehicleId] as const,
  serviceCategories: ['service-categories'] as const,
  vehicleGroups: ['vehicle-groups'] as const,
  groupVehicles: (id: string) => ['vehicle-groups', id, 'vehicles'] as const,
  vehicle: (id: string) => ['vehicles', id] as const,
  vehicleSearch: (params: object) => ['vehicles', 'search', params] as const,
  vehicleOwnership: (id: string) => ['vehicles', id, 'ownership'] as const,
  customerVehicles: (customerId: string) => ['customers', customerId, 'vehicles'] as const,
  products: ['products'] as const,
  product: (id: string) => ['products', id] as const,
  quotes: (workOrderId: string) => ['work-orders', workOrderId, 'quotes'] as const,
  quote: (workOrderId: string, quoteId: string) => ['work-orders', workOrderId, 'quotes', quoteId] as const,
  quoteAccess: (workOrderId: string, quoteId: string) => ['work-orders', workOrderId, 'quotes', quoteId, 'public-access'] as const,
  publicQuote: (token: string) => ['public-quote', token] as const,
}
