import{render,screen,waitFor}from'@testing-library/react'
import userEvent from'@testing-library/user-event'
import{MemoryRouter}from'react-router-dom'
import{QueryClient,QueryClientProvider}from'@tanstack/react-query'
import{expect,test,vi}from'vitest'
import{AuthProvider}from'../auth/AuthProvider'
import App from'../App'
import{api,post}from'../api/http'
const session={id:'u1',name:'Operador',email:'op@teste.local',profileCode:'ADMIN',state:'ACTIVE',mustChangePassword:false,permissions:[]}
function json(body:unknown,status=200){return new Response(status===204?null:JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}})}
function mock(routes:Record<string,unknown>,current:typeof session|null=session){return vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const path=String(input),method=init?.method||'GET';if(path==='/api/iam/csrf')return json({headerName:'X-CSRF-TOKEN',parameterName:'_csrf',token:'test'});if(path==='/api/iam/session')return current?json(current):json({},401);if(path==='/api/iam/auth/login')return json(session);const key=`${method} ${path}`;return key in routes?json(routes[key],method==='POST'?201:200):json({message:'Falha simulada'},500)})}
function renderAt(path:string){const client=new QueryClient({defaultOptions:{queries:{retry:false}}});return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><AuthProvider><App/></AuthProvider></MemoryRouter></QueryClientProvider>)}
test('login usa sessão real e navega',async()=>{const f=mock({'GET /api/work-orders':[]},null);renderAt('/login');await userEvent.type(await screen.findByLabelText('E-mail'),'op@teste.local');await userEvent.type(screen.getByLabelText('Senha'),'segredo123');await userEvent.click(screen.getByRole('button',{name:'Entrar'}));await screen.findByRole('heading',{name:'Ordens de serviço'});expect(f).toHaveBeenCalledWith('/api/iam/auth/login',expect.objectContaining({credentials:'include'}))})
test('protege rota sem sessão',async()=>{mock({},null);renderAt('/clientes');expect(await screen.findByRole('heading',{name:'Entrar'})).toBeInTheDocument()})
test('mustChangePassword direciona alteração',async()=>{mock({}, {...session,mustChangePassword:true});renderAt('/clientes');expect(await screen.findByRole('heading',{name:'Alterar senha'})).toBeInTheDocument()})
test('CSRF usa header retornado em mutação',async()=>{const f=vi.spyOn(globalThis,'fetch').mockResolvedValueOnce(json({headerName:'X-DYNAMIC',parameterName:'x',token:'abc'})).mockResolvedValueOnce(json({},201));await post('/api/test',{ok:true});expect(new Headers(f.mock.calls[1][1]?.headers).get('X-DYNAMIC')).toBe('abc')})
test.each([['PF','/clientes/novo/pf','Nome completo *','12345678901'],['PJ','/clientes/novo/pj','Razão social *','12345678000199']])('cadastra cliente %s',async(_,path,label,document)=>{const f=mock({'POST /api/customers':{},'GET /api/customers':[]});renderAt(path);await userEvent.type(await screen.findByLabelText(label),'Cliente Teste');await userEvent.type(screen.getByLabelText(/CPF|CNPJ/),document);await userEvent.click(screen.getByRole('button',{name:'Salvar cliente'}));await waitFor(()=>expect(f).toHaveBeenCalledWith('/api/customers',expect.objectContaining({method:'POST'})));const request=f.mock.calls.find(call=>String(call[0])==='/api/customers')?.[1];expect(JSON.parse(String(request?.body))).toEqual({name:'Cliente Teste',document,personType:_,status:'ACTIVE'})})
test('seleção de cliente carrega somente seus veículos',async()=>{mock({'GET /api/customers':[{id:'c1',name:'Cliente API',status:'ACTIVE',personType:'PF',document:'1'}],'GET /api/customers/c1/vehicles':[{id:'v1',customerId:'c1',manufacturer:'Marca API',model:'Modelo API',plate:'AAA1A11'}]});renderAt('/ordens-servico/nova');await screen.findByRole('option',{name:'Cliente API'});await userEvent.selectOptions(screen.getByLabelText('Cliente'),'c1');expect(await screen.findByRole('option',{name:/Marca API/})).toBeInTheDocument()})
test('cadastro serviço envia contrato',async()=>{const f=mock({'POST /api/services':{},'GET /api/services':[]});renderAt('/servicos/novo');await userEvent.type(await screen.findByLabelText('Nome *'),'Alinhamento');await userEvent.type(screen.getByLabelText('Preço base *'),'120');await userEvent.type(screen.getByLabelText('Descrição *'),'Descrição API');await userEvent.click(screen.getByRole('button',{name:'Salvar serviço'}));await waitFor(()=>expect(f).toHaveBeenCalledWith('/api/services',expect.objectContaining({method:'POST'})));const request=f.mock.calls.find(call=>String(call[0])==='/api/services')?.[1];expect(JSON.parse(String(request?.body))).toMatchObject({name:'Alinhamento',description:'Descrição API',basePrice:120,defaultWarrantyDays:90,active:true})})
test('detalhe soma snapshots e permite inclusão',async()=>{const f=mock({'GET /api/work-orders/o1':{id:'o1',number:1,customerId:'c1',vehicleId:'v1',entryMileage:100,openedAt:'2026-09-10T10:00:00Z',status:'ABERTA',services:[{id:'i1',serviceId:'s1',name:'Serviço API',description:'Desc',basePrice:12.5,warrantyDays:90,addedAt:'2026-09-10T10:00:00Z'}]},'GET /api/services':[{id:'s2',name:'Segundo serviço',description:'D',category:null,basePrice:7.5,defaultWarrantyDays:90,active:true}],'GET /api/customers/c1':{id:'c1',name:'Cliente API'},'GET /api/vehicles/v1':{id:'v1',manufacturer:'Marca',model:'Modelo',plate:'AAA1A11'},'POST /api/work-orders/o1/services':{id:'o1'}});renderAt('/ordens-servico/o1');expect(await screen.findByTestId('subtotal')).toHaveTextContent('12,50');await userEvent.selectOptions(screen.getByLabelText('Catálogo ativo'),'s2');await userEvent.click(screen.getByRole('button',{name:'Adicionar à OS'}));await waitFor(()=>expect(f).toHaveBeenCalledWith('/api/work-orders/o1/services',expect.objectContaining({method:'POST'})));const request=f.mock.calls.find(call=>String(call[0])==='/api/work-orders/o1/services')?.[1];expect(JSON.parse(String(request?.body))).toEqual({serviceId:'s2'})})
test('erro da API aparece sem alert nativo',async()=>{mock({});renderAt('/clientes');expect(await screen.findByRole('alert')).toHaveTextContent('Não foi possível')})
test('dados do Figma não estão hardcoded',()=>{const modules=import.meta.glob(['../App.tsx','../auth/**/*.tsx','../components/**/*.tsx','../features/**/*.tsx'],{query:'?raw',import:'default',eager:true});expect(Object.values(modules).join('\n')).not.toContain('Carlos Henrique Souza')})
test('api tolera mutação 204',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValueOnce(json({headerName:'X',parameterName:'x',token:'t'})).mockResolvedValueOnce(json(null,204));await expect(api('/api/logout',{method:'POST'})).resolves.toBeUndefined()})
test('OS exige quilometragem preenchida',async()=>{const f=mock({'GET /api/customers':[{id:'c1',name:'Cliente API',status:'ACTIVE',personType:'PF',document:'1'}],'GET /api/customers/c1/vehicles':[{id:'v1',customerId:'c1',manufacturer:'Marca',model:'Modelo',plate:'AAA1A11'}]});renderAt('/ordens-servico/nova');await screen.findByRole('option',{name:'Cliente API'});await userEvent.selectOptions(screen.getByLabelText('Cliente'),'c1');await screen.findByRole('option',{name:/Marca/});await userEvent.selectOptions(screen.getByLabelText('Veículo'),'v1');await userEvent.click(screen.getByRole('button',{name:'Criar OS'}));expect(await screen.findByRole('alert')).toHaveTextContent('Informe a quilometragem');expect(f.mock.calls.some(call=>String(call[0])==='/api/work-orders')).toBe(false)})
